import type { Metadata } from 'next'
import Image from 'next/image'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import { SITE_URL, SITE_NAME, AUTHOR } from '@/lib/constants'
import { BLOG_SLUGS, POST_META, type BlogSlug } from '@/lib/blog-data'
import { PostHeroImage } from '@/components/blog/post-hero-image'
import { TableOfContents } from '@/components/blog/toc'
import { NewsletterSignup } from '@/components/blog/newsletter-signup'
import { RelatedPosts } from '@/components/blog/related-posts'
import { PLACEHOLDERS } from '@/lib/placeholders'

export function generateStaticParams() {
  return BLOG_SLUGS.map((slug) => ({ slug }))
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  const meta = POST_META[slug as BlogSlug]
  if (!meta) return {}
  return {
    title: meta.title,
    description: meta.description,
    alternates: { canonical: `${SITE_URL}/blog/${slug}` },
    openGraph: {
      title: meta.title,
      description: meta.description,
      type: 'article',
      publishedTime: meta.date,
      authors: [SITE_NAME],
      url: `${SITE_URL}/blog/${slug}`,
    },
  }
}

function CsrToSsrContent() {
  return (
    <div className="prose-site">
      <p>
        My old portfolio was a Create React App. It looked fine in the browser. A friend
        who works in SEO looked at it and said: &ldquo;Googlebot sees a blank page.&rdquo;
        I didn&apos;t believe him until I ran a Lighthouse audit and got 62 out of 100 for
        SEO. The Performance score was worse.
      </p>

      <h2>What CSR actually sends to the crawler</h2>
      <p>
        In a client-side rendered React app, the server sends a response that looks
        roughly like this:
      </p>
      <pre>
        <code>{`<!DOCTYPE html>
<html>
  <head>
    <script src="/static/js/main.abc123.js" defer></script>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>`}</code>
      </pre>
      <p>
        The actual content — your name, your services, your case studies — is all
        generated by JavaScript running in the browser. For a human on a fast connection,
        the experience is fine. The JS loads in under a second and React renders
        everything.
      </p>
      <p>
        Googlebot has a different experience. It does crawl JavaScript — eventually. But
        the rendering is queued separately from the initial crawl and can happen hours or
        days later, or not at all for low-priority pages. During the initial crawl, Google
        sees your empty <code>div#root</code> and indexes that.
      </p>
      <p>
        The practical result: your name, your experience, and your services might not be
        indexed at all. Or they might be indexed with a weeks-long delay, during which you
        rank for nothing.
      </p>

      <h2>The Core Web Vitals problem</h2>
      <p>
        CSR also tanks your Core Web Vitals, specifically LCP (Largest Contentful Paint) —
        the time until the page&apos;s main content is visible. With CSR, the browser has
        to download the HTML, then download the JavaScript bundle, then parse and execute
        it, then render the content. On a fast desktop connection you might get away with
        a 1–2 second LCP. On a mid-range Android device on a 4G connection in most of the
        world, you&apos;re looking at 3–5 seconds.
      </p>
      <p>
        Google uses Core Web Vitals as a ranking signal. A slow CSR portfolio isn&apos;t
        just hard to find — it&apos;s penalized in search results relative to pages that
        are fast.
      </p>

      <h2>SSG, SSR, and ISR — which one?</h2>
      <p>
        Next.js gives you three rendering strategies. For a portfolio, the choice is
        straightforward:
      </p>
      <p>
        <strong>Static Site Generation (SSG)</strong> is right for a portfolio. Your
        homepage, about page, and services pages don&apos;t change between requests.
        Next.js builds them at build time and serves static HTML. Googlebot gets the full
        content on the first crawl. LCP drops dramatically because the browser gets real
        content in the HTML, not an empty div.
      </p>
      <p>
        <strong>Server-Side Rendering (SSR)</strong> renders each page on request.
        It&apos;s better for SEO than CSR, but slower than SSG because each request incurs
        a server render. Use SSR for pages that depend on request-time data (user
        sessions, personalisation). A portfolio doesn&apos;t need this.
      </p>
      <p>
        <strong>Incremental Static Regeneration (ISR)</strong> is SSG with a time-based
        revalidation window. Good for blog pages that update occasionally — the page is
        static but Next.js regenerates it in the background every N seconds. I use ISR
        with a 24-hour window for my blog index.
      </p>

      <h2>The migration</h2>
      <p>
        I rebuilt the portfolio as a Next.js 16 App Router site. The architecture is
        straightforward:
      </p>
      <ul>
        <li>Homepage, about, services, contact — all static (SSG at build time)</li>
        <li>Blog index — ISR with 24-hour revalidation</li>
        <li>
          Blog posts — SSG with <code>generateStaticParams</code>
        </li>
        <li>OG image route — dynamic, edge runtime</li>
      </ul>
      <p>
        The biggest concrete win was the LCP. My old CRA portfolio had an LCP of 4.2
        seconds on a simulated Moto G4 in Lighthouse. The Next.js SSG version runs at 1.1
        seconds on the same simulation. That&apos;s not a configuration win — it&apos;s a
        fundamental architecture difference.
      </p>

      <h2>What actually improved in search</h2>
      <p>
        I ran the old CRA site for about 18 months. In Google Search Console, it showed 12
        indexed pages and essentially no impressions for anything meaningful. After
        switching to Next.js SSG and giving Google 6 weeks to re-crawl:
      </p>
      <ul>
        <li>Indexed pages: 12 → 31</li>
        <li>Search impressions: negligible → ~400/month</li>
        <li>Lighthouse SEO score: 62 → 100</li>
        <li>Lighthouse Performance (mobile): 48 → 91</li>
      </ul>
      <p>
        Is 400 impressions/month impressive? No. But it&apos;s a starting point that can
        grow. The CRA version had no starting point at all.
      </p>

      <h2>The takeaway</h2>
      <p>
        If you&apos;re a developer with a portfolio built in Create React App, Vite, or
        any other purely client-side setup — switch to Next.js SSG. It&apos;s not a
        difficult migration, and the SEO and performance difference is significant. The
        tools exist. There&apos;s no good reason to be invisible to search engines in
        2026.
      </p>
      <p>
        The irony of a developer&apos;s portfolio being unfindable via Google is real, and
        it&apos;s entirely avoidable.
      </p>
    </div>
  )
}

function ArgoCdContent() {
  return (
    <div className="prose-site">
      <p>
        I&apos;ve set up ArgoCD from scratch in eight different organizations. Every
        single one of them started with the same naive setup that&apos;s in every
        tutorial: one ArgoCD Application pointing at one Helm chart in one Git repository.
        This setup works fine until it doesn&apos;t — and the failure mode is always the
        same. You add a second service, then a third, and suddenly you&apos;re managing
        Application manifests by hand, drift is happening in ways you can&apos;t track,
        and the promise of GitOps feels more like a constraint than a superpower.
      </p>

      <h2>Why the naive setup fails</h2>
      <p>The typical ArgoCD tutorial shows you this:</p>
      <pre>
        <code>{`apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/org/my-app
    path: helm/my-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app`}</code>
      </pre>
      <p>
        This is fine for one app. At ten apps across three environments, you have 30
        Application manifests to manage. When you need to change a common sync policy or
        add a notification hook, you update 30 files. When a new service gets added,
        someone has to remember to create the Application manifests for dev, staging, and
        production. The manual overhead defeats the purpose.
      </p>

      <h2>The app-of-apps pattern</h2>
      <p>
        The solution is the app-of-apps pattern: one ArgoCD Application (the &ldquo;root
        app&rdquo;) that manages all other Applications. The root app syncs a directory of
        Application manifests from Git. When you add a new service, you add one
        Application manifest to that directory. ArgoCD picks it up automatically.
      </p>
      <pre>
        <code>{`# root-app.yaml — this is all you add to ArgoCD manually
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/org/gitops-config
    path: apps/production
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true`}</code>
      </pre>
      <p>
        The <code>apps/production/</code> directory in your config repo contains one
        Application manifest per service. Each Application manifest points at the
        service&apos;s Helm chart (either in the same config repo or in the application
        repo).
      </p>

      <h2>Repo structure</h2>
      <p>
        There are two schools of thought on repo structure: monorepo (application code and
        Helm charts in the same repo) and separate repos (application code in one repo,
        Kubernetes config in another). I&apos;ve used both. My preference:
      </p>
      <ul>
        <li>
          <strong>Separate config repo</strong> for anything serious. It gives you a clean
          audit trail of all Kubernetes configuration changes separate from application
          code. GitOps tools get confused when they have to watch a repo where most
          commits are application code changes, not config changes.
        </li>
        <li>
          <strong>Monorepo</strong> only for small teams where the overhead of maintaining
          two repos is real. The audit trail gets messy, but the DX is simpler.
        </li>
      </ul>
      <p>In the config repo, I use this structure:</p>
      <pre>
        <code>{`gitops-config/
├── apps/
│   ├── dev/          # Application manifests for dev cluster
│   ├── staging/
│   └── production/
├── charts/           # Shared Helm chart templates
└── values/
    ├── dev/          # Per-service values for dev
    ├── staging/
    └── production/`}</code>
      </pre>

      <h2>Sync policies — automated vs manual</h2>
      <p>
        The most common mistake I see: setting <code>automated: {'{}'}</code> sync on
        production. I understand the appeal — fully automated GitOps, merge to main and
        it&apos;s in production. But for most teams, production deploys should have a
        human gate.
      </p>
      <p>My standard policy:</p>
      <ul>
        <li>
          <strong>Dev:</strong> <code>automated: {'{prune: true, selfHeal: true}'}</code>{' '}
          — every merge to main auto-deploys to dev
        </li>
        <li>
          <strong>Staging:</strong> <code>automated: {'{prune: false}'}</code> —
          auto-syncs when config changes, but won&apos;t prune resources automatically
        </li>
        <li>
          <strong>Production:</strong> No automation — manual sync only, triggered via
          ArgoCD UI or argocd CLI, with a Slack notification via argocd-notifications
          before and after
        </li>
      </ul>
      <p>
        The production manual gate isn&apos;t about distrust of the automation — it&apos;s
        about having a named human who confirmed the deploy was intentional and was
        watching when it happened.
      </p>

      <h2>Secrets with External Secrets Operator</h2>
      <p>
        Never put secrets in your GitOps config repo, even encrypted. The pattern I use:
        External Secrets Operator (ESO) syncing from AWS Secrets Manager or HashiCorp
        Vault into Kubernetes Secrets. The config repo only contains ExternalSecret
        manifests — references to where the secret lives, not the secret value itself.
      </p>
      <pre>
        <code>{`apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: database-credentials
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /production/myapp/database
        property: password`}</code>
      </pre>
      <p>
        This is safe to commit. The secret value lives in AWS Secrets Manager. ESO syncs
        it into a Kubernetes Secret on schedule and whenever it changes. Rotation happens
        automatically.
      </p>

      <h2>Image update automation</h2>
      <p>
        For dev environments, I use Argo CD Image Updater to automatically update image
        tags when a new image is pushed to ECR. This removes the step where a developer
        has to manually bump the image tag in the config repo after CI builds a new image.
      </p>
      <p>
        For staging and production, image tags are pinned. A human (or a CI step with an
        explicit PR) bumps the tag. This is intentional — you want to know exactly what
        changed in each environment and be able to attribute it to a specific decision.
      </p>

      <h2>The thing that actually makes this work</h2>
      <p>
        Every ArgoCD setup I&apos;ve built that worked well had one thing in common: the
        team actually reviewed the ArgoCD sync diffs before approving production syncs.
        ArgoCD shows you exactly what&apos;s going to change — what resources will be
        added, modified, or deleted. Reviewing that diff is the human layer that catches
        the misconfigured environment variable, the accidentally removed service, the
        wrong replica count.
      </p>
      <p>
        GitOps doesn&apos;t remove the need for human judgment — it makes human judgment
        more efficient by surfacing exactly what needs to be reviewed.
      </p>
    </div>
  )
}

function TerraformVsPulumiContent() {
  return (
    <div className="prose-site">
      <p>
        I&apos;ve used Terraform for three years and Pulumi for two. I have production
        infrastructure running on both. My take: they&apos;re both good tools, and the
        tool choice is far less important than the workflows and conventions you build
        around whichever one you pick. That said — you asked which one to pick for a
        greenfield project, so here&apos;s my honest answer.
      </p>

      <h2>The state of each tool in 2026</h2>
      <p>
        <strong>Terraform</strong> (now OpenTofu for the open-source fork, Terraform for
        the HashiCorp enterprise version) is the incumbent. The provider ecosystem is
        unmatched — if a cloud service exists, there&apos;s a Terraform provider for it,
        and it&apos;s probably well-maintained. The HashiCorp Registry has 3,000+
        providers. HCL (HashiCorp Configuration Language) is opinionated and limited by
        design — you can&apos;t write a for loop that generates arbitrary resources based
        on runtime logic, and that constraint turns out to be mostly a feature.
      </p>
      <p>
        <strong>Pulumi</strong> lets you write infrastructure in TypeScript, Python, Go,
        Java, or .NET. Your infrastructure is a real program — you can use loops,
        conditionals, functions, testing frameworks, and every other language feature you
        already know. Pulumi has a growing provider ecosystem (most are wrappers around
        Terraform providers under the hood), a solid state backend, and first-class
        support for testing infrastructure logic.
      </p>

      <h2>When Terraform wins</h2>
      <p>
        <strong>You need breadth of providers.</strong> For anything beyond the major
        clouds, Terraform&apos;s provider ecosystem is deeper. If you&apos;re using
        Cloudflare, Datadog, PagerDuty, Vault, and three SaaS tools, Terraform has stable,
        well-documented providers for all of them. Pulumi often wraps Terraform providers,
        which works but sometimes lags on updates.
      </p>
      <p>
        <strong>Your team isn&apos;t all software engineers.</strong> DevOps engineers,
        SREs, and sysadmins who are comfortable with YAML and shell scripting often find
        HCL more approachable than a real programming language for infrastructure work.
        The explicit, declarative nature of HCL means you can read a Terraform file and
        know what it will do without understanding control flow.
      </p>
      <p>
        <strong>You want a large community and existing examples.</strong> Any
        infrastructure pattern you want to implement — VPC design, EKS cluster, RDS setup
        — has been done in Terraform, documented, and probably open-sourced. The Terraform
        Registry module ecosystem is huge.
      </p>

      <h2>When Pulumi wins</h2>
      <p>
        <strong>You need to test your infrastructure logic.</strong> Pulumi supports unit
        and integration testing using standard testing frameworks. You can write a test
        that verifies your VPC doesn&apos;t have public subnets in production, or that
        every resource has required tags. Terraform&apos;s testing story (terraform test)
        is improving but still limited compared to what you can do with a real testing
        framework.
      </p>
      <p>
        <strong>Your infrastructure is highly dynamic.</strong> If you&apos;re generating
        dozens of similar resources based on external data (e.g., creating one Route53
        record per entry in a config file, or one IAM role per team in a list),
        Pulumi&apos;s programming model is much cleaner than Terraform&apos;s{' '}
        <code>for_each</code> and <code>dynamic</code> blocks.
      </p>
      <p>
        <strong>Your team is primarily software engineers.</strong> If everyone already
        knows TypeScript and the infrastructure team is the same people as the application
        team, Pulumi removes the context-switch into HCL. Testing infrastructure the same
        way you test application code is a real workflow win.
      </p>

      <h2>The one thing that matters more than the tool</h2>
      <p>
        I&apos;ve seen terrible Terraform codebases and terrible Pulumi codebases. The
        tool isn&apos;t the variable. The pattern I see in bad infrastructure code,
        regardless of tool:
      </p>
      <ul>
        <li>No module or component abstraction — everything in one flat directory</li>
        <li>State stored locally (or worse, not at all)</li>
        <li>
          No CI/CD for infrastructure changes — people run <code>apply</code> from their
          laptops
        </li>
        <li>No code review for infrastructure changes</li>
        <li>Hardcoded values instead of variables</li>
        <li>No drift detection</li>
      </ul>
      <p>
        These problems exist independently of whether you picked Terraform or Pulumi. A
        team with good IaC conventions will succeed with either. A team without them will
        fail with both.
      </p>

      <h2>My recommendation for greenfield in 2026</h2>
      <p>
        <strong>Default to Terraform (OpenTofu)</strong> unless you have a specific reason
        not to. The ecosystem maturity, the community, and the amount of existing
        reference material give you a faster start. If you&apos;re on AWS with a standard
        setup, the hashicorp/aws provider is excellent and will cover everything you need.
      </p>
      <p>
        <strong>Consider Pulumi if:</strong> your team is software engineers who write
        TypeScript or Python daily, you need serious infrastructure testing, or your
        infrastructure is genuinely dynamic in ways that Terraform&apos;s{' '}
        <code>for_each</code> handles awkwardly.
      </p>
      <p>
        Whatever you pick, invest in the workflow: remote state with locking (S3 +
        DynamoDB for Terraform, Pulumi Cloud or self-hosted for Pulumi), CI/CD with plan
        on PR and apply on merge, consistent module structure, and mandatory code review
        for infrastructure changes. That&apos;s what makes the difference between
        infrastructure you trust and infrastructure you&apos;re afraid to touch.
      </p>
    </div>
  )
}

const ARTICLE_CONTENT: Record<BlogSlug, React.ReactNode> = {
  'csr-to-ssr-seo': <CsrToSsrContent />,
  'pragmatic-argocd-gitops': <ArgoCdContent />,
  'terraform-vs-pulumi-2026': <TerraformVsPulumiContent />,
}

export default async function BlogPostPage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const meta = POST_META[slug as BlogSlug]
  if (!meta) notFound()

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: meta.title,
    datePublished: meta.date,
    author: { '@type': 'Person', name: SITE_NAME, url: SITE_URL },
    publisher: { '@type': 'Person', name: SITE_NAME, url: SITE_URL },
    url: `${SITE_URL}/blog/${slug}`,
    description: meta.description,
  }

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c'),
        }}
      />

      {/* Full-bleed post hero */}
      <div className="mx-auto max-w-6xl px-4 pt-16 sm:px-6 lg:px-8">
        <nav className="text-fg-muted mb-10 text-sm" aria-label="Breadcrumb">
          <Link href="/" className="hover:text-foreground transition-colors">
            Home
          </Link>
          <span className="text-fg-subtle mx-2">/</span>
          <Link href="/blog" className="hover:text-foreground transition-colors">
            Writing
          </Link>
          <span className="text-fg-subtle mx-2">/</span>
          <span className="text-foreground inline-block max-w-[200px] truncate align-bottom">
            {meta.title.slice(0, 40)}…
          </span>
        </nav>
      </div>

      <div className="mx-auto max-w-6xl px-4 pb-4 sm:px-6 lg:px-8">
        <PostHeroImage
          category={meta.category}
          src={PLACEHOLDERS.blogPostHero(slug)}
          className="aspect-[21/9] w-full rounded-xl"
        />
      </div>

      <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 gap-16 lg:grid-cols-[1fr_220px]">
          <article className="min-w-0">
            {/* Header */}
            <header className="mb-10">
              <div className="text-fg-subtle mb-4 flex items-center gap-3 font-mono text-xs">
                <span className="border-border rounded-full border px-2.5 py-0.5">
                  {meta.category}
                </span>
                <span>·</span>
                <time dateTime={meta.date}>{meta.date}</time>
                <span>·</span>
                <span>{meta.readTime} read</span>
              </div>
              <h1 className="max-w-[22ch] text-4xl font-bold tracking-[-0.025em] [text-wrap:balance]">
                {meta.title}
              </h1>
            </header>

            {/* Content */}
            {ARTICLE_CONTENT[slug as BlogSlug]}

            {/* Newsletter before author */}
            <NewsletterSignup />

            {/* Author card */}
            <div className="card-surface mt-4 rounded-xl p-6">
              <div className="mb-3 flex items-center gap-3">
                {/* PLACEHOLDER-IMG: Replace with real author photo */}
                <Image
                  src={PLACEHOLDERS.blogAuthorAvatar}
                  alt={SITE_NAME}
                  width={40}
                  height={40}
                  className="h-10 w-10 flex-shrink-0 rounded-full object-cover object-top"
                />
                <p className="text-foreground text-sm font-semibold">{SITE_NAME}</p>
              </div>
              <p className="text-fg-muted mb-4 text-sm">
                Freelance DevOps &amp; cloud engineer. Kubernetes, CI/CD, AWS, and web
                development for startups across the US, EU, and MENA.
              </p>
              <div className="flex flex-wrap gap-3">
                <Link
                  href="/about"
                  className="text-accent-primary hover:text-accent-primary/80 text-sm transition-colors"
                >
                  About me
                </Link>
                <Link
                  href="/contact"
                  className="text-accent-primary hover:text-accent-primary/80 text-sm transition-colors"
                >
                  Work with me
                </Link>
                <a
                  href={AUTHOR.twitter}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-accent-primary hover:text-accent-primary/80 text-sm transition-colors"
                >
                  X / Twitter
                </a>
              </div>
            </div>

            {/* Related posts */}
            <RelatedPosts currentSlug={slug as BlogSlug} />

            <nav className="mt-10 flex items-center" aria-label="Post navigation">
              <Link
                href="/blog"
                className="text-fg-muted hover:text-foreground inline-flex items-center gap-1.5 text-sm transition-colors"
              >
                <ArrowLeft size={13} aria-hidden /> All posts
              </Link>
            </nav>
          </article>

          {/* Sticky sidebar */}
          <aside className="hidden lg:block">
            <div className="sticky top-24 space-y-4">
              {/* Table of contents */}
              <div className="card-surface rounded-xl p-5">
                <TableOfContents />
              </div>

              <div className="card-surface rounded-xl p-5">
                <h3 className="text-fg-subtle mb-4 font-mono text-xs font-semibold tracking-[0.2em] uppercase">
                  Work with me
                </h3>
                <p className="text-fg-muted mb-4 text-xs leading-relaxed">
                  Need help with Kubernetes, CI/CD, or AWS infrastructure?
                </p>
                <div className="space-y-2">
                  <Link
                    href="/book"
                    className="bg-accent-primary hover:bg-accent-primary/90 block w-full rounded-lg px-3 py-2 text-center text-xs font-semibold text-white transition-colors"
                  >
                    Book a 30-min call
                  </Link>
                  <Link
                    href="/contact"
                    className="border-border text-foreground hover:bg-bg-raised block w-full rounded-lg border px-3 py-2 text-center text-xs font-medium transition-colors"
                  >
                    Send a brief <ArrowRight size={11} className="inline" aria-hidden />
                  </Link>
                </div>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </>
  )
}
